### ISSUE TITLE
Warning message "Iterable.length has been deprecated, use iterable.size or iterable.count()" when using ImmutableJS list as items

### ISSUE THREAD

**Issue by pnuzhdin** [seatgeek/react-infinite#37]
There is following warning. Where React.createClass.getInitialState has been called for Infinite.getInitialState() for the line "numberOfChildren: this.props.children.length,". Looks like it was caused by using ImmutableJS list as items for react-infinite component.

iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at List.Object.defineProperty.get (http://localhost:8000/dist/bundle.js:15254:21)
    at React.createClass.getInitialState (http://localhost:8000/dist/bundle.js:29042:44)
    at new Constructor (http://localhost:8000/dist/bundle.js:41561:54)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:8000/dist/bundle.js:42085:16)
    at wrapper [as mountComponent] (http://localhost:8000/dist/bundle.js:49297:21)
    at Object.ReactReconciler.mountComponent (http://localhost:8000/dist/bundle.js:50114:35)
    at Object.__REACT_INSPECTOR_RUNTIME__0_13_0.React.ReactReconciler.mountComponent (<anonymous>:106:41)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (http://localhost:8000/dist/bundle.js:48734:44)
    at ReactDOMComponent.Mixin._createContentMarkup (http://localhost:8000/dist/bundle.js:43492:32)
    at ReactDOMComponent.Mixin.mountComponent (http://localhost:8000/dist/bundle.js:43402:12)

**Comment by garetht** [comment]
Related issue: https://github.com/facebook/immutable-js/issues/236
